- hosts: localhost
  connection: local
  become: true
  vars:
    packages:
            #      - google-chrome-stable
      - git
      - ftp
      - jq
      - telnet
      - netcat
      - socat
      - rdesktop
      - nbtscan
      - tmux
      - vim
      - python
      - python-pip
      - python3
      - python3-pip
      - samba
      - cifs-utils
      - python-impacket
      - python-scapy
      - python3-scapy
      - scanssh
      - nmap
      - zenmap
      - sqlmap
        #      - wpscan
      - dnsrecon
      - ncrack
      - onesixtyone
      - cewl
      - john
      - hashcat
      - hydra
      - recon-ng
      - aircrack-ng
      - airgraph-ng
      - kismet
      - wireshark
      - hunt
      - mdbtools
      - p7zip-full
      - pst-utils
      - libimage-exiftool-perl
      - beef
  tasks:
    - name: install deb packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
