- hosts: localhost
  connection: local
  become: true
  vars:
    packages:
      - nbtscan
      - samba-common-bin
      - smbclient
      - polenum
      - ldap-utils
      - samba
      - cifs-utils
      - python-scapy
      - python3-scapy
      - scanssh
      - zenmap
      - sqlmap
      - dnsrecon
      - ncrack
      - onesixtyone
      - cewl
      - john
      - hashcat
      - hydra
      - recon-ng
      - aircrack-ng
      - airgraph-ng
      - kismet
      - wireshark
      - hunt
      - mdbtools
      - p7zip-full
      - pst-utils
      - libimage-exiftool-perl
      - steghide  
      - beef
  tasks:
    - name: install deb packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
